Tracker:AddLocations("locations/Beenie Death.json")
Tracker:AddLocations("locations/Beenie Factory.json")
Tracker:AddLocations("locations/Beenie HQ.json")
Tracker:AddLocations("locations/Behrman Speedway.json")
Tracker:AddLocations("locations/Bildal Mines.json")
Tracker:AddLocations("locations/Blimbo City.json")
Tracker:AddLocations("locations/Blimbo Village.json")
Tracker:AddLocations("locations/Canyon.json")
Tracker:AddLocations("locations/Chamber.json")
Tracker:AddLocations("locations/Chicken Farm.json")
Tracker:AddLocations("locations/Church.json")
Tracker:AddLocations("locations/Cleaners.json")
Tracker:AddLocations("locations/Cliffs of Nowher.json")
Tracker:AddLocations("locations/Cricket.json")
Tracker:AddLocations("locations/Desert.json")
Tracker:AddLocations("locations/Dry Zone.json")
Tracker:AddLocations("locations/FRIDGE WORLD.json")
Tracker:AddLocations("locations/Fields.json")
Tracker:AddLocations("locations/Fish Vore.json")
Tracker:AddLocations("locations/Forest.json")
Tracker:AddLocations("locations/Garden.json")
Tracker:AddLocations("locations/Gym.json")
Tracker:AddLocations("locations/Hat Store.json")
Tracker:AddLocations("locations/Howth.json")
Tracker:AddLocations("locations/Mikk Barge.json")
Tracker:AddLocations("locations/Municipal Wastes.json")
Tracker:AddLocations("locations/Museum.json")
Tracker:AddLocations("locations/Norwich.json")
Tracker:AddLocations("locations/Office.json")
Tracker:AddLocations("locations/Petrol Station.json")
Tracker:AddLocations("locations/Raccoon Central Station.json")
Tracker:AddLocations("locations/THE MACHINE.json")
Tracker:AddLocations("locations/The Gully.json")
Tracker:AddLocations("locations/The Process.json")
Tracker:AddLocations("locations/Trasco Carpark.json")
Tracker:AddLocations("locations/Tyre World.json")
Tracker:AddLocations("locations/Underground Metro.json")
Tracker:AddLocations("locations/Water Zone.json")
Tracker:AddLocations("locations/Overworld.json")
