Tracker:AddLocations("locations/Beenie Factory.json")
Tracker:AddLocations("locations/Beenie HQ Back.json")
Tracker:AddLocations("locations/Beenie HQ Front.json")
Tracker:AddLocations("locations/Beenie HQ Inside.json")
Tracker:AddLocations("locations/Bildal Mines.json")
Tracker:AddLocations("locations/Blimbo City.json")
Tracker:AddLocations("locations/Blimbo City Bottom Main.json")
Tracker:AddLocations("locations/Blimbo City Girders.json")
Tracker:AddLocations("locations/Blimbo City Middle.json")
Tracker:AddLocations("locations/Blimbo City Middle Back.json")
Tracker:AddLocations("locations/Blimbo City Middle Casino.json")
Tracker:AddLocations("locations/Blimbo City PURGATORY.json")
Tracker:AddLocations("locations/Blimbo City Pub.json")
Tracker:AddLocations("locations/Blimbo City Reactor.json")
Tracker:AddLocations("locations/Blimbo City Top.json")
Tracker:AddLocations("locations/Blimbo City Upper Towers.json")
Tracker:AddLocations("locations/Blimbo Village Start.json")
Tracker:AddLocations("locations/Blimbo Village Town.json")
Tracker:AddLocations("locations/Canyon.json")
Tracker:AddLocations("locations/Canyon Pharmacy.json")
Tracker:AddLocations("locations/Desert.json")
Tracker:AddLocations("locations/Dry Zone.json")
Tracker:AddLocations("locations/FRIDGE WORLD.json")
Tracker:AddLocations("locations/Garden.json")
Tracker:AddLocations("locations/Gym Inside.json")
Tracker:AddLocations("locations/Gym Outside.json")
Tracker:AddLocations("locations/Howth End.json")
Tracker:AddLocations("locations/Howth Start.json")
Tracker:AddLocations("locations/Municipal Wastes.json")
Tracker:AddLocations("locations/Museum.json")
Tracker:AddLocations("locations/Norwich.json")
Tracker:AddLocations("locations/Office.json")
Tracker:AddLocations("locations/Petrol Station.json")
Tracker:AddLocations("locations/Raccoon Central Station.json")
Tracker:AddLocations("locations/The Gully.json")
Tracker:AddLocations("locations/The Process.json")
Tracker:AddLocations("locations/Trasco Carpark.json")
Tracker:AddLocations("locations/Trasco Carpark Piss Shrine.json")
Tracker:AddLocations("locations/Water Zone.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Act 1 Cluster.json")
Tracker:AddLocations("locations/Act 2 Cluster.json")
Tracker:AddLocations("locations/Act 3 Cluster.json")
Tracker:AddLocations("locations/Act 4 Cluster.json")
